In [1]:
import pandas as pd
from pathlib import Path

In [15]:
root = Path("../../data")
file = root / "main.csv"

In [6]:
Path().absolute()

PosixPath('/Users/anton/Projects/vogelring/src/processor')

In [33]:
df = pd.read_csv(file, sep=";")
df = df.drop(
    [
        "Koordinaten",
        "IngLong",
        "IngLat",
        "Spalte1",
        "Tag",
        "Monat",
        "Jahr",
        "strSpecies",
        "strRingScheme",
        "Nummer",
        "Bein",
        "Ort3",
        "Unnamed: 26",
        "Datum2",
        "dtmDate",
        "strSex",
        "strAge",
        "Alter",
    ],
    axis=1,
)
df.head()

,Art,RingString,Ablesung,Datum,Ort,Gruppengröße,Bemerkung,Melder,gemeldet
0,Nilgans,HE2,HE2,5/19/11,Alte Brücke,45,NaN,NaN,577
1,Kanadagans,290379,290 379,2/24/19,Ostpark,31 (278962/…/970/…279000/ 290379/; außerdem: (...,NaN,IR,
2,Graugans,274848,274848,4/17/19,Ostpark,solo,NaN,IR,?
3,Graugans,290334,290 334,6/29/20,Höchst Stadtpark,Gesamt 53 (21),flugfähig,IR,?
4,Graugans,290335,290 335,7/19/19,Höchst Stadtpark,NaN,NaN,"Usinger, H.",?

In [35]:
def to_int_or_nan(x):
    try:
        return int(x)
    except (ValueError, TypeError):
        return pd.NA


df["Gruppengröße"] = df["Gruppengröße"].apply(to_int_or_nan)

# Show the results
df.head()

,Art,RingString,Ablesung,Datum,Ort,Gruppengröße,Bemerkung,Melder,gemeldet
0,Nilgans,HE2,HE2,5/19/11,Alte Brücke,45,NaN,NaN,577
1,Kanadagans,290379,290 379,2/24/19,Ostpark,<NA>,NaN,IR,
2,Graugans,274848,274848,4/17/19,Ostpark,<NA>,NaN,IR,?
3,Graugans,290334,290 334,6/29/20,Höchst Stadtpark,<NA>,flugfähig,IR,?
4,Graugans,290335,290 335,7/19/19,Höchst Stadtpark,<NA>,NaN,"Usinger, H.",?

In [40]:
# Remove quotes from both columns
df["Bemerkung"] = df["Bemerkung"].str.replace('"', "").str.replace("'", "")
df["Melder"] = df["Melder"].str.replace('"', "").str.replace("'", "")
df["Ort"] = df["Ort"].str.replace('"', "").str.replace("'", "")

In [44]:
# Drop rows where any of these columns are empty
print(f"Shape before dropping empty rows: {df.shape}")
df = df.dropna(subset=["Art", "RingString", "Ablesung"])

# Show the results and the new shape
print(f"Shape after dropping empty rows: {df.shape}")

Shape before dropping empty rows: (6639, 9)
Shape after dropping empty rows: (6639, 9)

In [45]:
df.to_csv(root / "out" / "main.csv")

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
infile = Path("/Users/anton/Documents/export-jan-5/main.csv")
df = pd.read_csv(infile, sep=";")
df.head()

,Art,strSpecies,RingString,Nummer,Ablesung,strRingScheme,Bein,Datum,Ort,lat,...,Tag,Monat,Jahr,dtmDate,Ort3,IngLong,IngLat,strSex,strAge,Unnamed: 36
0,Blässgans,NaN,NaN,NaN,V 8L,NaN,NaN,1/2/23,"Riedstadt, Fuchsloch","49,867222",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bläss-x Graugans,1610.0,282320,282320,…320,DEW,NaN,6/30/20,"F, Ostpark","50,120676",...,31.0,5.0,2020,2020-05-31 00:00:00,"Frankfurt, Ostpark*[DEED, 5818)",8.72333,50.12028,0,4.0,NaN
2,Bläss-x Graugans,1610.0,282320,282320,…320,NaN,NaN,12/27/20,"F, Ostpark","50,120676",...,31.0,5.0,2020,2020-05-31 00:00:00,"Frankfurt, Ostpark*[DEED, 5818)",8.72333,50.12028,0,4.0,NaN
3,Bläss-x Graugans,1610.0,282320,282320,…82320,NaN,NaN,2/12/21,"F, Main F-A, N","50,108983",...,31.0,5.0,2020,2020-05-31 00:00:00,"Frankfurt, Ostpark*[DEED, 5818)",8.72333,50.12028,0,4.0,NaN
4,Bläss-x Graugans,1610.0,282320,282320,NaN,NaN,NaN,2/27/21,"F, Ostpark","50,120676",...,31.0,5.0,2020,2020-05-31 00:00:00,"Frankfurt, Ostpark*[DEED, 5818)",8.72333,50.12028,0,4.0,NaN

In [13]:
# Get unique combinations of Ort and Ort2 columns
unique_places = df[["Ort", "Ort 2"]].drop_duplicates().dropna()

unique_places

                                        Ort                   Ort 2
1                                F, Ostpark                      GW
7                                F, Ostpark                     OSI
9                                F, Ostpark                 GW/OSVI
24                               F, Ostpark                   OSIII
28                           F, Main A-E, N                      NU
31                        F, Weselerwerft N              Skaterpark
35                     Offenbacher Mainufer                     HdB
78                               F, Ostpark                   Kiosk
79                               F, Ostpark                      NU
81                               F, Ostpark                      SW
84                               F, Ostpark                   Cetto
109                              F, Ostpark                    OSIV
110                              F, Ostpark                    OSVI
246                              F, Ostpark                   B8III
271                              F, Ostpark                    B8IV
360                  OF, Carl-Ulrich-Brücke                   P Ost
389                              F, Ostpark            Bürgergarten
404                              F, Ostpark                 GW/OSIV
422                              F, Ostpark                     GW
427                              F, Ostpark                    OSII
431                              F, Ostpark               Kioskufer
486                              F, Ostpark                      SU
518                              F, Ostpark                    OSI
561                              F, Ostpark                      OW
573                              F, Ostpark                      WU
657   OF Rumpenheim, LSG Hess. Mainauen Ost                   Cetto
763                              F, Ostpark            Cetto, B8III
901                              F, Ostpark             B8III/Cetto
976                              F, Ostpark                     OSV
1019                             F, Ostpark                    OSV
1030                             F, Ostpark                   OSII
1216                         F, Main I-E, S      Ignaz-Bubis-Brücke
1628                       F, Portikusinsel                   IGB S
1702                             F, Ostpark                      GE
2091                  F, Römerstadt, Altarm              Römerstadt
2116                        F, Nidda RL-A66               Praunheim
2915                 OF, Carl-Ulrich-Brücke                      GW
5188                      F, Friedensbrücke                      NU
5225                         F, Main U-H, S                      SU
5371                         F, Main A-E, N                Nordufer
5464                             F, Ostpark                      OU
5758                       F, Portikusinsel                      NU
5761                       F, Portikusinsel                      SU
5764                       F, Portikusinsel                      SO
6037                             F, Ostpark                      SP
6052                      F, Friedensbrücke                      SU
6151                         F, Main F-B, S                      SU
6179                        F, Rebstockpark                      OU
6192                        F, Rebstockpark                 NO Ufer
6211                        F, Rebstockpark                      SU
6411                      F, Friedensbrücke                      NW
6461                             F, Ostpark                   GW/SU
6481               F, Griesheimer Staustufe                      NU
6551                        F, Rebstockpark                      NU
6639                        F, Rebstockpark                      WU
6694                        F, Nidda A66-A5               Rödelheim
6866                         F, Main F-B, S  T.Heus-Kai (Uniklinik)

In [18]:
unique_places.to_csv(root / "out" / "unique_places.csv", index=False, sep=";")